# Generated by Django 4.0.1 on 2022-02-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='anonymous', max_length=14, verbose_name='Username'),
        ),
    ]
