# Generated by Django 4.0.3 on 2022-04-09 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f41da733-be48-46c2-871e-16f2ff7baef2'), primary_key=True, serialize=False),
        ),
    ]
