# Generated by Django 4.0.3 on 2022-04-10 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('382e8f8d-24ac-4bc9-9286-45dd4da4a128'), primary_key=True, serialize=False),
        ),
    ]
