# Generated by Django 4.0.3 on 2022-04-09 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('18d42220-8b8f-4c85-b0c7-962e84ffb47a'), primary_key=True, serialize=False),
        ),
    ]
