# Generated by Django 4.0.3 on 2022-04-10 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e537528f-1cf5-44f7-b867-dd78d6ba92c4'), primary_key=True, serialize=False),
        ),
    ]
