# Generated by Django 4.0.1 on 2022-02-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
