# Generated by Django 4.0.3 on 2022-04-01 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(\\.?[a-z0-9])*[a-z0-9]+@[a-z0-9\\-]*\\.[a-z]{1,20}$', message='Invalid email')], verbose_name='Email'),
        ),
    ]
