# Generated by Django 4.0.4 on 2022-04-22 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d260a1ee-83dd-4d36-bbc7-b9a1e94a159d'), primary_key=True, serialize=False),
        ),
    ]
