# Generated by Django 4.0.3 on 2022-03-31 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]{3,18}$', message="Username should be between 3-18 characters, and must contain letters, numbers, or '_' only.")], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(\\.?[a-z0-9])*[a-z0-9]+@[a-z0-9\\-]*\\.[a-z]{2,3}$', message='Invalid email')], verbose_name='Email'),
        ),
    ]
