# Generated by Django 4.0.4 on 2022-04-25 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('88712be7-1a28-49ad-b12f-bc7d871caa20'), primary_key=True, serialize=False),
        ),
    ]
