# Generated by Django 4.0.4 on 2022-05-14 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ab6855af-3fb6-4ca4-89db-477a8d12f87e'), primary_key=True, serialize=False),
        ),
    ]
