# Generated by Django 4.0.4 on 2022-05-14 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f1f1c3fe-2cf0-4792-b751-ba4dae36e863'), primary_key=True, serialize=False),
        ),
    ]
