# Generated by Django 4.0.4 on 2022-05-17 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fe2e8015-8987-4c18-8bc2-efe0f05e457c'), primary_key=True, serialize=False),
        ),
    ]
