# Generated by Django 4.0.4 on 2022-05-17 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('19885e5a-35d9-40e8-8b58-108276a597de'), primary_key=True, serialize=False),
        ),
    ]
