# Generated by Django 4.0.4 on 2022-05-17 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cb98966a-71c2-41c8-8f66-524e7ab3d60a'), primary_key=True, serialize=False),
        ),
    ]
