# Generated by Django 4.0.4 on 2022-05-17 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c566a76d-f5d9-4c61-8205-dc4d609bcbde'), primary_key=True, serialize=False),
        ),
    ]
