# Generated by Django 4.0.4 on 2022-05-18 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b6d488a1-b155-4e0c-96a8-ccd80ce1b91c'), primary_key=True, serialize=False),
        ),
    ]
