# Generated by Django 4.0.4 on 2022-05-18 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('55757376-6981-4a4c-9f67-fd834ad20614'), primary_key=True, serialize=False),
        ),
    ]
