# Generated by Django 4.0.4 on 2022-05-18 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a99cab57-525b-4325-9e02-25071b1f3476'), primary_key=True, serialize=False),
        ),
    ]
