# Generated by Django 4.0.4 on 2022-05-19 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e4e39a99-9666-454c-8548-6131741468d2'), primary_key=True, serialize=False),
        ),
    ]
