# Generated by Django 4.0.1 on 2022-01-10 09:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('featureimage', models.ImageField(upload_to='core/article/%Y/%m/')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(default='slug', max_length=500)),
                ('tags', models.CharField(default='untagged', max_length=500)),
                ('writer', models.CharField(default='Leroy Buliro', max_length=100)),
                ('credit', models.CharField(blank=True, max_length=700, null=True)),
                ('publishdate', models.DateField()),
                ('extract', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='core/events/%Y/%m/')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='core/podcast/')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('appleurl', models.URLField(max_length=255, unique=True)),
                ('googleurl', models.URLField(max_length=255, unique=True)),
                ('spotifyurl', models.URLField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('tags', models.CharField(default='untagged', max_length=500)),
                ('image', models.ImageField(upload_to='core/podcast/')),
                ('summary', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('audio', models.FileField(upload_to='core/podcast/')),
                ('pubDate', models.DateField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.podcast')),
            ],
            options={
                'db_table': 'podcast_episode',
                'ordering': ['-episode'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=400)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
            ],
            options={
                'db_table': 'article_comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.articlecategory'),
        ),
    ]
