# Generated by Django 4.0.4 on 2022-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestat',
            name='visited',
            field=models.DateTimeField(default='2022-05-17T10:16:18+03:00'),
        ),
    ]
