# Generated by Django 4.0.4 on 2022-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestat',
            name='visited',
            field=models.DateTimeField(default='2022-05-15T00:19:21+03:00'),
        ),
    ]
