# Generated by Django 4.0.1 on 2022-02-09 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 16, 25, 36, 934704)),
        ),
    ]
