# Generated by Django 4.0.1 on 2022-01-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=500)),
                ('ratings', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-postdate'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=420)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
            ],
            options={
                'db_table': 'article_comment',
                'ordering': ['-postdate'],
            },
        ),
    ]
