# Generated by Django 3.2.9 on 2021-11-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articlecategory_mailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='core/events/%Y/%m/')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-date'],
            },
        ),
    ]
