# Generated by Django 4.0.1 on 2022-02-10 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articlestat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 14, 38, 5, 246038, tzinfo=utc)),
        ),
    ]
