# Generated by Django 4.0.1 on 2022-01-29 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback_articlecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='0.0.0.0')),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 14, 32, 43, 98439))),
            ],
            options={
                'db_table': 'article_stat',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='articlestat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
    ]
