# Generated by Django 4.0.4 on 2022-04-25 18:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('featureimage', models.ImageField(upload_to='core/article/%Y/%m/')),
                ('featureimageURI', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('writer', models.CharField(default='Leroy Buliro', max_length=100)),
                ('credit', models.CharField(blank=True, max_length=700, null=True)),
                ('publishdate', models.DateField()),
                ('extract', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-publishdate'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'article_tag',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='core/events/%Y/%m/')),
                ('posterURI', models.URLField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='0.0.0.0')),
                ('device', models.CharField(default='null', max_length=400)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            options={
                'db_table': 'article_stat',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=420)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
            ],
            options={
                'db_table': 'article_comment',
                'ordering': ['-postdate'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.articlecategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='core.articletag'),
        ),
    ]
