# Generated by Django 3.2.9 on 2021-11-22 11:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('featureimage', models.ImageField(upload_to='core/article/%Y/%m/')),
                ('title', models.CharField(max_length=500)),
                ('writer', models.CharField(default='Leroy Buliro', max_length=100)),
                ('credit', models.CharField(blank=True, max_length=700, null=True)),
                ('publishdate', models.DateField()),
                ('extract', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.articlecategory')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
