# Generated by Django 4.0.1 on 2022-01-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='article',
        ),
    ]
