# Generated by Django 4.0.4 on 2022-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_shares_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestat',
            name='visited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
