# Generated by Django 4.0.1 on 2022-01-29 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articlestat_remove_article_views_delete_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestat',
            name='device',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 16, 1, 34, 512956)),
        ),
    ]
