# Generated by Django 4.0.1 on 2022-02-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_articlestat_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestat',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlestat',
            name='created',
        ),
    ]
