# Generated by Django 4.0.1 on 2022-01-29 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articlestat_device_alter_articlestat_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'article_tag',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 16, 32, 38, 232415)),
        ),
        migrations.AlterField(
            model_name='articlestat',
            name='device',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='core.ArticleTag'),
        ),
    ]
