# Generated by Django 4.0.1 on 2022-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_feedback_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publishdate']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-postdate']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(default='Article', max_length=500),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sourceId',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
