# Generated by Django 4.0.1 on 2022-01-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_articletag_alter_article_shares_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 22, 29, 29, 752738)),
        ),
        migrations.AlterField(
            model_name='articlestat',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
