# Generated by Django 3.2.9 on 2021-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='untagged', max_length=500),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='tags',
            field=models.CharField(default='untagged', max_length=500),
        ),
    ]
