# Generated by Django 4.0.1 on 2022-01-31 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_articlestat_created_alter_articlestat_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestat',
            name='session',
        ),
        migrations.AlterField(
            model_name='articlestat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 14, 39, 57, 649049)),
        ),
    ]
