# Generated by Django 3.2.9 on 2021-12-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211222_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mailinglist',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='slug', max_length=500),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.CharField(default='slug', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(default='slug', max_length=500),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='slug',
            field=models.CharField(default='slug', max_length=500),
        ),
    ]
