# Generated by Django 3.2.9 on 2021-12-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211223_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='slug',
            field=models.CharField(max_length=500),
        ),
    ]
