# Generated by Django 4.0.4 on 2022-05-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_comments_content_cd20f6_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_content_cd20f6_idx',
        ),
    ]
